### ISSUE TITLE
[FEATURE] Export to/Import from a Git repo

### ISSUE THREAD

**Issue by eruvanos** [awslabs/threat-composer#117]
### Describe the feature

It would be great to be able to export to or import from a GitHub repository.
Even better would be a default location, which could be configured within the workspace.

### Use Case

As a team, we want to collaborate on the threat model, for this we often export the workspace and store it in GitHub.

This process takes some time, for each change, which reduces the motivation to do small incremental updates.
Shorten this cycle, would improve the actuality of the threat model. Also it would reduce the frustration about merge conflicts due to a forgotten export/import.

### Proposed Solution

Allow to configure a default location for the workspace.
Allow import and export directly to the repo.

### Other Information

This should be possible using client side code.

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by dboyd13** [comment]
Does your team use Visual Studio Code? If yes, I believe the recent Threat Composer support we added to the [AWS Toolkit extension](https://marketplace.visualstudio.com/items?itemName=AmazonWebServices.aws-toolkit-vscode) would be useful for your use case. 

With it you can create, view and edit Threat Composer threat models directly within VSCode using the familiar web interface working on a local clone of your GitHub repository which can then be pushed to the origin using your standard git workflow. 

This feature was built to help drive the philosophy of threat models as code and integrating threat modeling practices into your development workflow by threat modeling right next to the thing you are building, and use the power of your version control system for persistence, version control, authorization, sharing and review.

Note that for this feature there is no need to be an AWs customer nor have an AWS account.

**Comment by eruvanos** [comment]
I just saw it. Thank you.
That is a good alternative, will this also be available for Jetbrains AWS Toolkit?

**Comment by dboyd13** [comment]
Great. No current plans for other IDEs - but please do file a feature request for your preferred IDE and we will track demand for it as part of future work prioritization

**Comment by dboyd13** [comment]
Closing this one
