### ISSUE TITLE
[FEATURE] Allow SVGs for diagrams

### ISSUE THREAD

**Issue by Pesir** [awslabs/threat-composer#84]
### Describe the feature

Allow vector Graphics e.g. SVG files in diagrams.

### Use Case

Instead of only allowing jpegs, pngs, etc,  also allow svg files. These are usually smaller and allow to scale text and information. And if the product changes and grows makes the very easy to edit since they are not static images.

### Proposed Solution

change
``` 
accept='image/png, image/gif, image/jpeg'
```
to
``` 
accept='image/*'
```
in ImageEdit 

### Acknowledgements

- [ ] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by jessieweiyi** [comment]
Hi @Pesir , thanks for raising the feature request. Does the image need to be stored as svg format on the platform? As currently, there is an image compression step after the file is uploaded. The SVG file will be converted into png.

**Comment by Pesir** [comment]
I would save it as an SVG, from what I saw the markdown rendering does support it for export. I would actually think compressing the svg to an png would increase image size. Svg is not pixel based so it only stores the actual shapes. It would also make delta changes so much nicer since svgs can be easily imported into draw.io or similar.
