### ISSUE TITLE
[FEATURE] Docker/Container Support for Deployment without an AWS account (e.g., Azure)

### ISSUE THREAD

**Issue by greckko** [awslabs/threat-composer#97]
### Describe the feature

Currently, Threat Composer is designed to run within AWS environments. This limitation restricts its usability for teams and organizations that operate in multi-cloud environments or primarily use services outside of AWS, such as Azure.

### Use Case

The adoption of containerized applications is growing, and providing a Docker version of Threat Composer could significantly increase its accessibility and utility. A containerized approach would also align with modern DevOps practices, making it easier for development and operations teams to integrate Threat Composer into their CI/CD pipelines.

### Proposed Solution

A Docker container version of Threat Composer. This containerized version would allow users to deploy Threat Composer in various environments, including Azure App Service, without significant modifications. It would greatly enhance the flexibility and adaptability of Threat Composer for diverse IT ecosystems.

### Acknowledgements

- [x] I may be able to implement this feature request
- [ ] This feature might incur a breaking change

**Comment by dboyd13** [comment]
@greckko Thanks for raising the feature request. We have added it into our backlog and are researching together with a previous PR #49
